apiVersion: v1
appVersion: 12.2.4
description: HTTP server for Gitlab
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
keywords:
- gitlab
- unicorn
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: unicorn
sources:
- https://gitlab.com/charts/gitlab/tree/master/charts/gitlab/charts/unicorn
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitlab-unicorn
version: 2.2.4
